export const SET_LOADING = 'SET_LOADING';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CREATE_THE_GAME = 'CREATE_THE_GAME';
export const CREATE_GAME_FAIL = 'CREATE_GAME_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';

export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const GET_GAMES = 'GET_GAMES';
export const GET_GAMES_ERROR = 'GET_GAMES_ERROR';
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const UPDATE_SCORE_ERROR = 'UPDATE_SCORE_ERROR';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_GAME_LOADING = 'SET_GAME_LOADING';

export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';

export const HIGHSCORE_UPDATE = 'HIGHSCORE_UPDATE';
export const HIGHSCORE_UPDATE_ERROR = 'HIGHSCORE_UPDATE_ERROR';



